
#' Build SummarizedExperiment object
#'
#' @description Converts a set of fcs files into SummarizedExperiment object for further analysis.
#'
#' @param input_folder               Path to folder containing raw fcs files.
#' @param experiment_info            Path to experiment_info table; one of the csv files generated by \code{\link{metadata_tables}}.
#' @param marker_info                Path to marker_info table; one of the csv files generated by \code{\link{metadata_tables}}.
#' @param output_folder              Path to folder to recieve the SummarizedExperiment object.
#' @param export                     If TRUE, the SummarizedExperiment object gets saved in the outpput_folder location.
#' @param arcsinh_cofactor           Cofactor value for the data arcsinh transformation. Default value is 5, which is the typically recommended data for mass cytometry.
#'                                   Recommended value for flow cytometry is 150.
#'
#' @seealso  \code{\link[SummarizedExperiment]{RangedSummarizedExperiment-class}} \code{\link[diffcyt]{prepareData}} \code{\link[flowCore]{read.flowSet}}
#'
#' @importFrom flowCore read.flowSet
#' @importFrom diffcyt prepareData
#' @importFrom Biobase isUnique
#'
#' @return SummarizedExperiment object
#'
#' @export

build_SE <- function(input_folder,
                     experiment_info,
                     marker_info,
                     output_folder = ".",
                     export = FALSE,
                     arcsinh_cofactor = NULL) {


  experiment_info <- suppressWarnings(read.csv(experiment_info, stringsAsFactors = TRUE))
  marker_info <- suppressWarnings(read.csv(marker_info, stringsAsFactors = TRUE))

  if (!all(isUnique(marker_info$clean_name))) {

    stop("clean_name in marker_info must be unique")

  }



  fcs_files <- list.files(path = input_folder, pattern = ".fcs$", full.names=TRUE, recursive = TRUE)
  all_files_set <- flowCore::read.flowSet(fcs_files, transformation = FALSE, truncate_max_range = FALSE)

  dir.create(file.path(output_folder, "RDS"), showWarnings = FALSE)

  SE <- diffcyt::prepareData (all_files_set,
                              experiment_info = experiment_info,
                              marker_info =  marker_info)


  if (export) {
    saveRDS(SE, file.path(output_folder,"RDS","SE.rds"))
  }

  if (!is.null(arcsinh_cofactor)){
    trans_SE <- asinh(assay(SE)/arcsinh_cofactor)

    saveRDS(trans_SE, file.path(output_folder,"RDS","trans_SE.rds"))
  }

  return(SE)

}
