#' Single-cell cytometry data workflow
#'
#'
#' @description This is a wrapper function around package 'Cytonalyze' to automate cytometry data analysis.
#'
#' @param input_folder            Path to folder containing fcs files.
#' @param SE                      SummarizedExperiment object or path to SummarizedExperiment object.
#' @param output_folder           Path to folder to receive output.
#' @param marker_info             Path to marker_info table; one of the csv files generated by \code{\link{metadata_tables}}.
#' @param experiment_info         Path to experiment_info table; one of the csv files generated by \code{\link{metadata_tables}}. It must have a "sample_id". And a
#'                                column "batch", if batch_correct is TRUE.
#' @param batch_correct           Logical. If TRUE, batch correction using 'cyCombine' package.
#' @param markers_correct         Character vector specifying the markers to be corrected for batch effect. It is recommended to run \code{\link[cyCombine]{detect_batch_effect}} to
#'                                define and evaluate markers that needs batch correction.
#' @param xdim                    The x-dimension size of the SOM. See \code{\link[cyCombine]{batch_correct}}.
#' @param ydim                    The y-dimension size of the SOM. See \code{\link[cyCombine]{batch_correct}}.
#' @param k                       Integer. k paramter for phenograph clustering. See \code{\link{k_sweep}}
#' @param n                       Integer. The size of local neighborhood (n_neigbors paramter of UMAP). See \code{\link[umap]{umap}}
#' @param assay_name              A single character vector indicates the assay to be used in plotting the UMAP. By default, it is \code{exprs}.
#' @param plot_clusters           Logical. If TRUE, \code{\link{cyto_umap}} is called to plot phenograph clusters on umap axes.
#' @param DS                      Integer. Specifies the number of cell to downsample to for the umap plots. If groups are provided, this number will be used to downsample from each group.
#' @param groups                  Character vector specifying the experimental group e.g c("control, "treated").
#' @param filter                  A character vector of all the levels in 'groups' that need to be filtered out of the analysis. Default is NULL.
#' @param exp_subject             Character vector specifying the experimental subject e.g c("mouse1", "mouse2").
#' @param plot_samples_prop       Logical. If TRUE, \code{\link{cyto_samples_barplot}} is called to plot cluster proportion in each sample in "sample_id".
#' @param samples                 Character. Represents the column name in the metadata to plot the sample barplot for.
#' @param plot_clusters_violin    Logical. If TRUE, \code{\link{cyto_clust_violin}} is called to plot marker intensity per cluster.
#' @param plot_cluster_corr       Logical. If TRUE, \code{\link{cyto_clust_corr}} is called to plot correlation matrix between clusters in samples and groups.
#' @param plot_cluster_colsPie    Logical. If TRUE, \code{\link{cyto_clust_colsPie}} is called to plot proportions of clusters in each group in a column plot and pie chart.
#' @param plot_cluster_hm         Logical. If TRUE, \code{\link{cyto_clust_hm}} is called to plot heatmap for the median marker intensity per cluster.
#' @param diff_exprs              Logical. If TRUE, \code{\link{cyto_diff_exprs}} is called to perform differential expression test using 'CytoGLMM'.
#' @param count_threshold         Integer. Clusters with cell count that are equal or less than this value will be excluded from the CytoGLMM differential expression analysis.
#' @param diff_abund              Logical. If TRUE, \code{\link{cyto_clust_abundance}} is called to perform differential abundance test using 'diffcyt' and 'edgeR'.
#' @param diff_limma              Logical. If TRUE, \code{\link{cyto_clust_limma}} is called to perform differential expression test using 'diffcyt' and' limma'.
#' @param contrast                A character vector of length 2, specify two levels of "groups" variable to build contrast matrix. \code{(contrast[1]-constrast[2])}.
#' @param paired                  Logical. If TRUE, paired experimental design is taken in consideration for all the statistical tests. The pairing is done on the column provided in \code{exp_subject}.
#' @param seed                    Setting random seed for results reproducibility. It can be NULL.
#' @param ...                     Additional arguments to any of the functions used in the wrapper.
#'
#'
#' @import SummarizedExperiment
#' @importFrom cyCombine convert_flowset
#' @importFrom cyCombine batch_correct
#' @importFrom diffcyt prepareData
#' @importFrom dplyr select
#' @importFrom dplyr %>%
#'
#' @return
#' A variety of R objects, tables and figures for cytometry data analysis exported to 'output_folder'.
#'
#' @export
#'
#'
cyto_workflow <- function (input_folder,
                           SE = NULL,
                           output_folder,
                           marker_info,
                           experiment_info,
                           batch_correct = FALSE,
                           markers_correct = NULL,
                           xdim = 8,
                           ydim = 8,
                           k = 30,
                           n = 15,
                           assay_name = "exprs",
                           plot_clusters = TRUE,
                           DS = 5000,
                           groups = NULL,
                           filter = NULL,
                           exp_subject = "sample_id",
                           plot_samples_prop = TRUE,
                           samples = "donor_id",
                           plot_clusters_violin = TRUE,
                           plot_cluster_corr = TRUE,
                           plot_cluster_colsPie = TRUE,
                           plot_cluster_hm = TRUE,
                           diff_exprs = TRUE,
                           count_threshold = 100,
                           num_boot = 1000,
                           diff_abund = TRUE,
                           diff_limma = TRUE,
                           contrast = NULL,
                           paired = FALSE,
                           seed = 7439815,
                           ...) {


  if (!dir.exists(output_folder)) {
    stop("output_folder does not exist.")
  }

  # Throw an error message if groups is missing and diff stats are TRUE.
  if (any(diff_exprs, diff_abund, diff_limma)) {
    stopifnot('Must specify argument "groups" to perform differential statistics.'= !is.null(groups))
    stopifnot('Must specify argument "exp_subject" to perform differential statistics.'= !is.null(exp_subject))
  }

  # Throw an error if contrast is missing and diff stats are TRUE.
  if (any(diff_abund, diff_limma)) {
    stopifnot('Must specify argument "contrast" to perform differential statistics.'= !is.null(contrast))

  }

  # The function will take one argument, either SE or input_folder.
  if (!is.null(SE) & !is.null(input_folder)){
    stop("The function can take only one argument either SE or input_folder.")
  }

  set.seed(seed)


 if(!is.null(SE)) {
   if(is.character(SE)) {
     SE <- readRDS(SE)
   } else if (is(SE, "SummarizedExperiment")) {
     NULL
   } else {
     stop("SE argument needs to a SummarizedExerpiment object or a path to SummarizedExperiment object.")
   }
 }


if (!is.null(input_folder)) {

  if(!is.character(input_folder)){
    stop("input_folder needs to the path for the fcs files.")
  }

  # Read file paths
  fcs_files <- list.files(path = input_folder,
                          pattern = ".fcs$",
                          full.names=TRUE)

  experiment_info <- read.csv(experiment_info, stringsAsFactors = TRUE)
  marker_info <- read.csv(marker_info)

  dir.create(file.path(output_folder, "RDS"), recursive = TRUE, showWarnings = FALSE)



  # Read fcs files into a flowSet
  message("Reading flowSet...")
  all_files_set <- flowCore::read.flowSet(fcs_files, transformation = FALSE, truncate_max_range = FALSE)

  # creating SummarizedExperiment from flowSet either with batch correction or without.

  if (batch_correct) {

    stopifnot("Please specify which markers to correct for batch effect" = !is.null(markers_correct))

    # clean desc on the flowSet
    for (i in 1:length(all_files_set)) {

      for (j in 1:nrow(all_files_set[[i]]@parameters@data["desc"])) {

        if (is.na(all_files_set[[i]]@parameters@data[j,"desc"]) ) {

          all_files_set[[i]]@parameters@data[j,"desc"] <- all_files_set[[i]]@parameters@data[j,"name"]
        }

      }

      all_files_set[[i]]@parameters@data$desc <-  stringi::stri_replace_all_regex (all_files_set[[i]]@parameters@data$desc,
                                                                                   pattern =c("^(.*?)_", "EQ", ":", "::", "-"),
                                                                                   replacement = c(""),
                                                                                   vectorize_all = FALSE)

      all_files_set[[i]]@parameters@data$desc <- make.names(all_files_set[[i]]@parameters@data$desc)
    }


    # create SummarizedExperiment object, whose rowdata and coldata will be used later.
    SE <- diffcyt::prepareData (all_files_set,
                                experiment_info = experiment_info,
                                marker_info = marker_info)

    row.names(colData(SE)) <- make.names(colData(SE)$clean_name)




    # create a tibble from the flowSet
    uncorrected <- convert_flowset(all_files_set,
                                   metadata = experiment_info,
                                   filename_col = "sample_id",
                                   batch_ids = "batch",
                                   down_sample = FALSE)

    # make sure colData and column names if uncorrect tibble matchs
    colnames(uncorrected)[2:(ncol(uncorrected)-2)]  <- rownames(colData(SE))

    # Correcting selected markers
    corrected <- batch_correct(uncorrected,
                               markers =  markers_correct)

    # Reorder column names of corrected tibble
    corrected_reordered <- corrected %>% select(rownames(colData(SE)))

    # Creating SummarizedExperiment with the corrected values
    message("Creating SummarizedExperiment...")
    SE <- SummarizedExperiment::SummarizedExperiment(assay =  as.matrix(corrected_reordered),
                                                     rowData = rowData (SE),
                                                     colData = colData(SE),
                                                     metadata = metadata(SE))
    names(assays(SE)) <- "exprs"

    message("Saving SummarizedExperiment...")
    saveRDS(SE, file.path(output_folder, "RDS", "corrected_SE.rds"))

    message("SummarizedExperiment is saved.")

  } else {
    message("Creating SummarizedExperiment...")
    SE <- diffcyt::prepareData (all_files_set,
                                experiment_info = experiment_info,
                                marker_info = marker_info)
    message("Saving SummarizedExperiment...")
    saveRDS(SE, file.path(output_folder, "RDS", "SE.rds"))

    message("SummarizedExperiment is saved.")

  }

}


  if (!is.null(filter) ) {

    message("filtering ", filter, "from the data." )

    for (i in filter) {

      SE <- SE[rowData(SE)[,groups] != i, ]

    }

    rowData(SE)[,groups] <- droplevels(rowData(SE)[,groups])

    message("The levels of ", groups, " are now:  ", paste(levels(rowData(SE)[,groups]), collapse  = ' '))
  }

  # Running Phenograph and UMAP

  message("Cellular clustering and dimensionality reduction...")
  SE_pheno_umap <- pheno_umap(SE,
                              marker_info = marker_info,
                              k = k,
                              n = n,
                              output_folder = output_folder,
                              export = TRUE,
                              assay_name = assay_name)


  # visualizations

errors <- c()

tryCatch({
    if (plot_clusters) {

    cyto_umap(SE_pheno_umap,
              output_folder = output_folder,
              groups = groups,
              DS = DS)

  }},
  error = function(e) {
    print(e)
    errors <<- c(errors, "Something went wrong with generating umap plot(s). You can generate umap plot(s) from the exported SummarizedExperiment using cyto_umap() from CytoAnalyze package.")
   }
  )


  tryCatch({
    if (plot_samples_prop) {

    cyto_samples_barplot(SE_pheno_umap,
                         samples = samples,
                         output_folder = output_folder)
  }},
  error = function(e) {
    print(e)
    errors <<- c(errors, "Something went wrong with generating samples/clusters proportions plot. You can generate the plot from the exported SummarizedExperiment using cyto_samples_barplot() from CytoAnalyze package.")
  }
  )



 tryCatch({
    if (plot_clusters_violin) {

    cyto_clust_violin(SE_pheno_umap,
                      output_folder = output_folder,
                      groups = groups)
  }},
  error = function(e) {
    print(e)
    errors <<- c(errors, "Something went wrong with generating violin plot(s). You can generate violin plot(s) from the exported SummarizedExperiment using cyto_clust_violin() from CytoAnalyze package.")
  }
  )


 tryCatch({
    if (plot_cluster_corr) {

    cyto_clust_corr(SE_pheno_umap,
                    output_folder = output_folder,
                    groups = groups)

  }},
  error = function(e) {
    print(e)
    errors <<- c(errors, "Something went wrong with generating correlation plot(s). You can generate correlation plot(s) from the exported SummarizedExperiment using cyto_clust_corr() from CytoAnalyze package.")
  }
  )


  tryCatch({
    if (plot_cluster_colsPie) {

    cyto_clust_colsPie(SE_pheno_umap,
                       output_folder = output_folder,
                       groups = groups)
    }},
    error = function(e) {
      print(e)
      errors <<- c(errors, "Something went wrong with generating pie chart and/or column bar to clusters proportion per group. You can generate the plots from the exported SummarizedExperiment using cyto_clust_colsPie() from CytoAnalyze package.")
    }
  )


  tryCatch({
    if (plot_cluster_hm) {

    cyto_clust_hm(SE_pheno_umap,
                  output_folder = output_folder)

  }},
  error = function(e) {
    #print(e)
    errors <<- c(errors, "Something went wrong with generating cluster/marker heatmap. You can generate the heatmap from the exported SummarizedExperiment using cyto_clust_hm() from CytoAnalyze package.")
  }
  )


  # statistics

  # CytoGLMM

  tryCatch({
    if (diff_exprs) {

    cyto_diff_exprs(SE_pheno_umap,
                    output_folder = output_folder,
                    count_threshold = count_threshold,
                    groups = groups,
                    num_boot = num_boot,
                    paired = paired)

  }},
  error = function(e) {
    print(e)
    errors <<- c(errors, "Something went wrong with performing CytoGLMM differential expression test. You can rerun it separately from the exported SummarizedExperiment using cyto_diff_exprs() from CytoAnalyze package.")
  }
  )


  # edgeR

  tryCatch({
    if(diff_abund) {
    cyto_clust_abundance(SE_pheno_umap,
                         output_folder = output_folder,
                         groups = groups,
                         exp_subject = exp_subject,
                         contrast = contrast,
                         paired = paired)
  }},
  error = function(e) {
    print(e)
    errors <<- c(errors, "Something went wrong with performing edgeR/diffcyt differential abundace test. You can rerun it separately from the exported SummarizedExperiment using cyto_clust_abundance() from CytoAnalyze package.")
  }
  )


  #limma

  tryCatch({
    if(diff_limma) {

    cyto_clust_limma(SE_pheno_umap,
                     output_folder = output_folder,
                     groups = groups,
                     contrast = contrast,
                     exp_subject = exp_subject,
                     paired = paired)
  }},
  error = function(e) {
    print(e)
    errors <<- c(errors, "Something went wrong with performimg limma/diffcyt differential expression test. You can rerun it separately from the exported SummarizedExperiment using cyto_clust_limma() from CytoAnalyze package.")
  }
  )

  if (length(errors) == 0) {
    cat("\033[32mNo errors occured.\n\033[0m")
  } else {
    cat("\033[32mThe following errors occured:", paste(errors, collapse = "\n"), "\033[0m", sep = "\n")
  }

  set.seed(NULL)

}

