#' Density-dependent Downsampling
#'
#' @description Downsample individual fcs files based on calculating local density for each single cell.
#'              For more details, see \code{\link[spade]{SPADE.addDensityToFCS}}.
#'
#' @param input_folder         Path to folder containing raw fcs files.
#' @param output_folder        Path to folder to receive downsample fcs files.
#' @param marker_info          Path to marker_info; one of the csv files generated by \code{\link{metadata_tables}}. Only markers that are labelled "type"
#'                             will be used to calculate cell density.
#' @param experiment_info      Path to experiment_info; one of the csv files generated by \code{\link{metadata_tables}}.
#' @param arcsinh_cofactor     Cofactor value for the data arcsinh transformation. Default value is 5, which is the typically recommended data for mass cytometry.
#'                             Recommended value for flow cytometry is 150.
#' @param density_to_exclude   Cells below this density value will be excluded. Default is 0.01 percentile.
#' @param density_to_preserve  Cells between this density value and the \option{density_to_exclude} value will be kept untouched.
#'                             Cells above this value will be downsampled till their density matches this value. Default is 0.3 percentile.
#' @param percent_events_keep  Percent of cells per file to keep after the downsampling. e.g the lowest 50% in density.
#'                             A numeric from 0 to 1.
#' @param number_events_keep   Number of events per file to keep. This will downsample approximately equal number of events per file.
#' @param ...                  Extra arguments passed to \code{\link[spade]{SPADE.addDensityToFCS}}.
#'
#'
#' @note   For more information; see \href{https://www.rdocumentation.org/packages/spade/versions/1.20.0}{spade}
#'
#' @details If \code{number_events_keep} is chosen to downsample individual files to a certain number of cells, files with cell count below, equal or 500 more than the value provided
#' will be skipped, and files with cell count. Files above the value provided + 500 will be downsampled to the provided value. The 500 added is just to make sure the script find enough cells
#' to downsample from after \code{density_to_exclude} remove cells.
#'
#' @import spade tools
#' @return Two folders; the first contains all the input fcs files with additional parameter added "density" added to the list of parameters.
#'         The second folder contains the downsampled fcs files.
#'
#' @seealso  \code{\link[spade]{SPADE.addDensityToFCS}}, \code{\link[spade]{SPADE.downsampleFCS}}
#' @references \href{https://www.nature.com/articles/nbt.1991}{Extracting a cellular hierarchy from high-dimensional cytometry data with SPADE}
#'
#'
#' @export



DDDsample <- function(input_folder,
                      output_folder,
                      marker_info,
                      experiment_info,
                      arcsinh_cofactor = NULL,
                      density_to_exclude = 0.01,
                      density_to_preserve = 0.03,
                      percent_events_keep = NULL,
                      number_events_keep = NULL,
                      ...)  {


  if (!all(colnames(marker_info) %in% c("channel_name","marker_name", "marker_class", "arcsinh_cofactor"))) {

    stop(paste("marker_info is missing a column or has incorrect column names"))
  }


  if (!all(is.character(input_folder) & is.character(output_folder))) {
    stop(paste("paths need to be character strings"))
  }


  if(is.numeric(number_events_keep) & !is.null(density_to_preserve)){
    stop(paste("density_to_preserve - number_events_keep: Only one argument needs to be specified."))
  }


  if(is.numeric(percent_events_keep) & !is.null(density_to_preserve)){
    stop(paste("density_to_preserve - percent_events_keep: Only one argument needs to be specified."))
  }


  if(is.numeric(number_events_keep) & is.numeric(percent_events_keep) ) {
    stop(paste("number_events_keep - percent_events_keep:Only one argument needs to be specified."))
  }



  # save path to marker_info and experiment_info before reading it, to be able to overwrite the original file later in the script.
  marker_info_path <- marker_info
  experiment_info_path <- experiment_info

  # read tables
  marker_info <- read.csv(marker_info)
  experiment_info <- read.csv(experiment_info)

  fcs_files <- list.files(path = input_folder, pattern = ".fcs$", full.names=TRUE, recursive = TRUE)

  if(length(fcs_files) == 0){
    stop("Input_folder does not contain any fcs files.")
  } else {
    cat(length(fcs_files), "files were found and will be down-sampled.\n")
  }

  dir.create(file.path(output_folder,"density_output"), showWarnings = FALSE)
  dir.create(file.path(output_folder,"downsample_output"), showWarnings = FALSE)

# Calculating density for individual files

  for (file in fcs_files) {

    message("calculating local density for ", file)
    suppressWarnings(
      spade::SPADE.addDensityToFCS(infilename =  file,
                                   outfilename = file.path(output_folder, "density_output", paste0(tools::file_path_sans_ext(basename(file)),"_density_added.fcs")),
                                   arcsinh_cofactor = arcsinh_cofactor,
                                   cols = marker_info[marker_info$marker_class == "type", "channel_name"],
                                   transforms = flowCore::arcsinhTransform(a=0, b=1),
                                   comp = FALSE
      )
    )
  }

# update and overwrite the marker_info and experiment_info table, with the new added channel/row "density" and filename.
  marker_info[nrow(marker_info)+1,] <- c("density", "density", "density", "none", "non_biological", rep("none", ncol(marker_info)-5))
  write.csv(x= marker_info, file=marker_info_path, row.names = FALSE)
  message("\nOriginal marker_info table has been overwritten by the updated marker_info table with the density parameter added.\n")

  fcs_files <- list.files(path = file.path(output_folder,"density_output"),
                          pattern = ".fcs$", full.names = TRUE)

  # Downsampling

  if (is.null(number_events_keep)) {

    for (file in fcs_files) {
      message("down-sampling...", file)
      suppressWarnings(
        spade::SPADE.downsampleFCS(infilename= file,
                                   outfilename = file.path(output_folder, "downsample_output", paste0(tools::file_path_sans_ext(basename(file)),"_DDDsampled.fcs")),
                                   exclude_pctile = density_to_exclude,
                                   target_pctile = density_to_preserve,
                                   target_percent = percent_events_keep,
                                   target_number =  number_events_keep)
      )
    }


  }


  if (is.numeric(number_events_keep)) {

    for (file in fcs_files) {

      temp <- flowCore::read.FCS(file, transformation = FALSE, truncate_max_range = FALSE)

      if (nrow(temp) > number_events_keep+500) {

        message("down-sampling...", file)
        suppressWarnings(
          spade::SPADE.downsampleFCS(infilename = file,
                                     outfilename = file.path(output_folder, "downsample_output", paste0(tools::file_path_sans_ext(basename(file)),"_DDDsampled.fcs")),
                                     exclude_pctile = 0,
                                     target_pctile = NULL,
                                     target_percent = NULL,
                                     target_number = number_events_keep)
        )

      } else {

        message("skipping down-sampling...", file)
        flowCore::write.FCS(temp, file.path(output_folder,  "downsample_output", paste0(tools::file_path_sans_ext(basename(file)),"_DDDsampled.fcs")))
      }
    }

  }


  fcs_files <- list.files(path = file.path(output_folder,"downsample_output"),
                          pattern = ".fcs$", full.names = TRUE)
  experiment_info$sample_id <- basename(fcs_files)
  write.csv(x=experiment_info, file=experiment_info_path, row.names = FALSE)
  message('\nOriginal experiment_info table has been overwritten by the updated experiment_info table with "DDDsampled" add to filename.')

  message("\nDown-sampled fcs files exported to ", file.path(output_folder, "downsample_output"))
}

