#' PhenoGraph clustering and UMAP dimensionality reduction

#' @description Assigns a phenograph cluster and calculate UMAP axes coordinates for cytometry single-cell data from cellular protein marker expression values,
#'
#' @param SE               SummarizedExperiment object or path to \code{SummarizedExperiment} object
#' @param marker_info      Path to marker_info table; one of the csv files generated by \code{\link{metadata_tables}}.
#' @param k                The number of nearest-neighbours to be used in building PhenoGraph.
#' @param n                A umap parameter that controls how UMAP balances local versus global structure in the data.
#' @param export           If \code{TRUE}, \code{SummarizedExperiment} object is exported and saved in the specified destination.
#' @param output_folder    Destination folder to recieve the outcome. Working directory is the default.
#' @param assay_name       Single character vector of the name of the \code{assay()} slot to be used in clustering.
#' @param ...              Additional arguments to \code{\link[Rphenograph]{Rphenograph}} and \code{\link[umap]{umap}}.
#'
#' @return  SummarizedExperiment object with a cluster_ID column and UMAP coordinates added. Data can be accessed through the \code{rowData()} accessor.
#'
#' @references   \href{https://www.nature.com/articles/nbt.4314}{UMAP}
#'               \href{https://www.cell.com/cell/fulltext/S0092-8674(15)00637-6?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867415006376%3Fshowall%3Dtrue}{PhenoGraph}
#'
#' @seealso  \href{https://bioconductor.org/packages/devel/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html}{Assorted clustering diagnostics}.
#'
#' @importFrom methods is
#' @import umap
#' @import Rphenograph
#'
#' @export



pheno_umap <- function(SE,
                       marker_info,
                       k=30,
                       n=15,
                       export=FALSE,
                       output_folder= ".",
                       assay_name = "exprs",
                       ...) {

  if (!dir.exists(output_folder)) {
    stop("output_folder does not exist.")
  }


  if(is.character(marker_info)) {
  marker_info <- suppressWarnings(read.csv(marker_info))
  }

  if (is.character(SE)) {
    SE <- readRDS(SE)
  }


  if (is(SE, "SummarizedExperiment")) {

    marker_flag <- colData(SE)$marker_class == "type"
    expr_mat <- assay(SE,assay_name)[,marker_flag]

    ## Phenograph clustering
    #Assigin each cells to a cluster ID
    pheno <- Rphenograph::Rphenograph(expr_mat, k, verbose = TRUE)

    #Add new column of cluster IDs to the data.
    rowData(SE)$cluster_id <- as.factor(igraph::membership(pheno[[2]]))

    ## Dimensions Reduction - UMAP
    #UMAP configurations
    umap.defaults$n_neighbors <- n

    #run umap
    umap <- umap::umap (expr_mat, config= umap.defaults, verbose = TRUE)

    #Add the reduced two dimensions to the data
    rowData(SE)$UMAP1 <- umap$layout[,1]
    rowData(SE)$UMAP2 <- umap$layout[,2]

    print(umap$config)

  }


  if(export) {
    dir.create(file.path(output_folder, "RDS"), showWarnings = FALSE)
    saveRDS(SE, file.path(output_folder, "RDS", "pheno_umap_SE.rds"))
  }

  return(SE)
}




